### ISSUE TITLE
BUG: Webpage not responsive

### ISSUE THREAD

**Issue by RohitS2004** [RohitS2004/tic-tac-toe#1]
When you try to see the responsiveness of the webpage using the chrome tools, the whole layout gets distorted and doesn't look that much beautiful.

<img width="236" alt="image" src="https://github.com/RohitS2004/tic-tac-toe/assets/118826575/b8ea9616-7522-49ec-9b8c-b3698f51eb0f">

The Header and the background linear-gradient gets disoriented.

**Comment by Kenny4297** [comment]
Hi @RohitS2004, I have the solution! May I make a PR?

**Comment by RohitS2004** [comment]
Hi @Kenny4297 Sure if you want

**Comment by nikhil3113** [comment]
hey @RohitS2004 i can fix this bug, can i make a pull request?

**Comment by RohitS2004** [comment]
@nikhil3113 Sure go ahead
