### ISSUE TITLE
BUG: Game not terminated even after the player won or draw

### ISSUE THREAD

**Issue by RohitS2004** [RohitS2004/tic-tac-toe#2]
Issue:
After any one of the user has won the game, the other player is still able to make his/her turn which should not be happening.
Also when the game is draw the last player is able to change the inputs of the other player.

Expected behavior: 
The players should not be allowed not make another turn when any one of them has won the game.
After game draw no player should be allowed to make another turn.

<img width="946" alt="image" src="https://github.com/RohitS2004/tic-tac-toe/assets/118826575/a54e7dfa-edbf-4a03-b6cb-dfd52f18d8a4">

<img width="948" alt="image" src="https://github.com/RohitS2004/tic-tac-toe/assets/118826575/e1f5a6f3-3b27-41b9-b209-2a796fc41d70">

**Comment by Kenny4297** [comment]
@RohitS2004, may I be assigned to this? I know how to fix this issue.
